batch_sz=8
bert_model='bert-base-uncased'
image_model='resnet152'
data_path='datasets'
drop_img_percent=0.0
dropout=0.4
embed_sz=300
freeze_img=False
freeze_txt=False
glove_path=''
gradient_accumulation_steps=24
evaluation_steps=2000
hidden=[]
hidden_sz=768
img_embed_pool_type='avg'
img_hidden_sz=2048
include_bn=True
lr=1e-5
lr_factor=0.5
lr_patience=2
max_epochs=1
max_seq_len=128
model='mmbt_feat'
n_workers=2
name='multi_mmbt'
num_image_embeds=1
patience=10
savedir='addestramenti'
data_type='tsv'
seed=2021
task='fakenewsdet'
task_type='classification'
warmup=0.1
weight_classes=1
doc_extraction='Yes'
save_documents='Yes'
type_dataset='Politifact'
doc_training='inference'
top_k_extract=467