import configargparse

def get_parsed_args():
    parser = configargparse.ArgParser(default_config_files=['configurazione.conf'])
    parser.add('-c', '--my-config', required=True, is_config_file=True, help='config file path')
    get_args(parser)
    args, remaining_args = parser.parse_known_args()
    assert remaining_args == [], remaining_args
    return args

def get_args(parser):
    parser.add("--batch_sz", type=int, default=128)
    parser.add("--bert_model", type=str, default="bert-base-uncased")
    parser.add("--image_model", type=str, default="resnet152")
    parser.add("--data_path", type=str, default="/path/to/data_dir/")
    parser.add("--drop_img_percent", type=float, default=0.0)
    parser.add("--dropout", type=float, default=0.1)
    parser.add("--embed_sz", type=int, default=300)
    parser.add("--freeze_img", default=False)
    parser.add("--freeze_txt", default=False)
    parser.add("--glove_path", type=str, default="/path/to/glove_embeds/glove.840B.300d.txt")
    parser.add("--gradient_accumulation_steps", type=int, default=24)
    parser.add("--evaluation_steps", type=int, default=24)
    parser.add("--hidden", nargs="*", type=int, default=[])
    parser.add("--hidden_sz", type=int, default=768)
    parser.add("--img_embed_pool_type", type=str, default="avg", choices=["max", "avg"])
    parser.add("--img_hidden_sz", type=int, default=2048)
    parser.add("--include_bn", default=True)
    parser.add("--lr", type=float, default=1e-4)
    parser.add("--lr_factor", type=float, default=0.5)
    parser.add("--lr_patience", type=int, default=2)
    parser.add("--max_epochs", type=int, default=100)
    parser.add("--max_seq_len", type=int, default=512)
    parser.add("--model", type=str, default="bow")
    parser.add("--n_workers", type=int, default=12)
    parser.add("--name", type=str, default="nameless")
    parser.add("--num_image_embeds", type=int, default=1)
    parser.add("--patience", type=int, default=10)
    parser.add("--savedir", type=str, default="/path/to/save_dir/")
    parser.add("--data_type", type=str, default="jsonl")
    parser.add("--seed", type=int, default=123)
    parser.add("--task", type=str, default="mmimdb")
    parser.add("--task_type", type=str, default="multilabel", choices=["multilabel", "classification","extraction"])
    parser.add("--warmup", type=float, default=0.1)
    parser.add("--weight_classes", type=int, default=1)
    parser.add("--doc_extraction", type=str, default="No")
    parser.add("--save_documents", type=str, default="No")
    parser.add("--type_dataset", type=str, default="Snopes", choices=["Snopes", "Politifact"])
    parser.add("--doc_training", type=str, default="training", choices=["training", "inference"])
    parser.add("--top_k_extract", type=int, default=10)