# MMBT Fact-Checking - MuMiN Dataset Configuration (Multilingual)
# =================================================

# Model
batch_sz=8
bert_model=/root/bert_multilingual_local
image_model=resnet152
hidden_sz=768
dropout=0.4
num_image_embeds=3
img_hidden_sz=2048
img_embed_pool_type=avg
include_bn=True
model=mmbt

# Data
data_path=datasets
task=fakenewsdet
type_dataset=MuMiN
data_type=tsv
max_seq_len=128
drop_img_percent=0.0
n_workers=2

# Training
max_epochs=3
lr=2e-5
lr_factor=0.5
lr_patience=2
gradient_accumulation_steps=24
evaluation_steps=2000
warmup=0.1
patience=10
weight_classes=1
freeze_img=False
freeze_txt=False
task_type=classification
seed=2024

# Paths
savedir=models/checkpoints
name=mmbt_mumin

# Evaluation
is_evaluation=No
doc_extraction=No
save_documents=No
doc_training=training
top_k_extract=50
